// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type CreateBookDto = {
    /**
     * Nome da carteira de tesouraria
     */
    name: string;
};

export type Book = {
    [key: string]: unknown;
};

export type UpdateBookDto = {
    /**
     * Nome da carteira de tesouraria
     */
    name?: string;
};

export type CreateTradeDto = {
    /**
     * ID da carteira (Book) associada
     */
    bookId: string;
    /**
     * Direção da operação
     */
    side: 'BUY' | 'SELL';
    /**
     * Par de moedas
     */
    currencyPair: string;
    /**
     * Volume financeiro da operação
     */
    volume: number;
    /**
     * Taxa de câmbio de entrada contratada
     */
    entryRate: number;
    /**
     * Data da operação (ISO 8601). Se omitido, assume a data/hora atual.
     */
    tradeDate?: string;
};

export type Trade = {
    [key: string]: unknown;
};

export type UpdateTradeDto = {
    /**
     * ID da carteira (Book) associada
     */
    bookId?: string;
    /**
     * Direção da operação
     */
    side?: 'BUY' | 'SELL';
    /**
     * Par de moedas
     */
    currencyPair?: string;
    /**
     * Volume financeiro da operação
     */
    volume?: number;
    /**
     * Taxa de câmbio de entrada contratada
     */
    entryRate?: number;
    /**
     * Data da operação (ISO 8601). Se omitido, assume a data/hora atual.
     */
    tradeDate?: string;
};

export type TradeRiskDetailDto = {
    /**
     * UUID do Trade
     */
    tradeId: string;
    /**
     * Direção da operação
     */
    side: 'BUY' | 'SELL';
    /**
     * Par de moedas
     */
    currencyPair: string;
    /**
     * Volume total do Trade
     */
    volume: number;
    /**
     * Volume protegido por Hedges
     */
    hedgedVolume: number;
    /**
     * Volume desprotegido (exposto)
     */
    unhedgedVolume: number;
    /**
     * Percentual de cobertura individual (%)
     */
    hedgeRatioPercent: number;
    /**
     * Taxa de câmbio contratada
     */
    entryRate: number;
    /**
     * Cotação de mercado atual utilizada no cálculo
     */
    marketRate: number;
    /**
     * Lucro/Prejuízo Não Realizado (Unrealized PnL)
     */
    unrealizedPnl: number;
};

export type RiskReportResponseDto = {
    /**
     * UUID do Book analisado
     */
    bookId: string;
    /**
     * Nome da carteira
     */
    bookName: string;
    /**
     * Volume total exposto da carteira
     */
    totalExposedVolume: number;
    /**
     * Volume total protegido da carteira
     */
    totalHedgedVolume: number;
    /**
     * Percentual geral de cobertura do Book (%)
     */
    overallHedgeRatioPercent: number;
    /**
     * Classificação da saúde financeira do Book
     */
    healthStatus: 'HEALTHY' | 'WARNING' | 'CRITICAL';
    /**
     * Orientação automática do Motor de Risco
     */
    suggestedAction: string;
    /**
     * PnL consolidado não realizado da carteira
     */
    totalUnrealizedPnl: number;
    /**
     * Detalhamento de risco operação por operação
     */
    tradesDetails: Array<TradeRiskDetailDto>;
};

export type CreateHedgeDto = {
    /**
     * ID da operação (Trade) a ser protegida
     */
    tradeId: string;
    /**
     * Volume da proteção contratada
     */
    volume: number;
    /**
     * Taxa de câmbio travada para o Hedge
     */
    entryRate: number;
    /**
     * Data do hedge (ISO 8601). Se omitido, assume a data/hora atual.
     */
    hedgeDate?: string;
};

export type Hedge = {
    [key: string]: unknown;
};

export type UpdateHedgeDto = {
    /**
     * ID da operação (Trade) a ser protegida
     */
    tradeId?: string;
    /**
     * Volume da proteção contratada
     */
    volume?: number;
    /**
     * Taxa de câmbio travada para o Hedge
     */
    entryRate?: number;
    /**
     * Data do hedge (ISO 8601). Se omitido, assume a data/hora atual.
     */
    hedgeDate?: string;
};

export type BooksControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/books';
};

export type BooksControllerFindAllResponses = {
    /**
     * Lista de carteiras retornada com sucesso.
     */
    200: Array<Book>;
};

export type BooksControllerFindAllResponse = BooksControllerFindAllResponses[keyof BooksControllerFindAllResponses];

export type BooksControllerCreateData = {
    body: CreateBookDto;
    path?: never;
    query?: never;
    url: '/books';
};

export type BooksControllerCreateResponses = {
    /**
     * Carteira criada com sucesso.
     */
    201: Book;
};

export type BooksControllerCreateResponse = BooksControllerCreateResponses[keyof BooksControllerCreateResponses];

export type BooksControllerRemoveData = {
    body?: never;
    path: {
        /**
         * UUID da carteira
         */
        id: string;
    };
    query?: never;
    url: '/books/{id}';
};

export type BooksControllerRemoveResponses = {
    /**
     * Carteira removida com sucesso.
     */
    200: unknown;
};

export type BooksControllerFindOneData = {
    body?: never;
    path: {
        /**
         * UUID da carteira
         */
        id: string;
    };
    query?: never;
    url: '/books/{id}';
};

export type BooksControllerFindOneErrors = {
    /**
     * Carteira não encontrada.
     */
    404: unknown;
};

export type BooksControllerFindOneResponses = {
    /**
     * Carteira encontrada.
     */
    200: Book;
};

export type BooksControllerFindOneResponse = BooksControllerFindOneResponses[keyof BooksControllerFindOneResponses];

export type BooksControllerUpdateData = {
    body: UpdateBookDto;
    path: {
        /**
         * UUID da carteira
         */
        id: string;
    };
    query?: never;
    url: '/books/{id}';
};

export type BooksControllerUpdateResponses = {
    /**
     * Carteira atualizada com sucesso.
     */
    200: Book;
};

export type BooksControllerUpdateResponse = BooksControllerUpdateResponses[keyof BooksControllerUpdateResponses];

export type TradesControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/trades';
};

export type TradesControllerFindAllResponses = {
    /**
     * Lista de trades retornada com sucesso.
     */
    200: Array<Trade>;
};

export type TradesControllerFindAllResponse = TradesControllerFindAllResponses[keyof TradesControllerFindAllResponses];

export type TradesControllerCreateData = {
    body: CreateTradeDto;
    path?: never;
    query?: never;
    url: '/trades';
};

export type TradesControllerCreateResponses = {
    /**
     * Trade criado com sucesso.
     */
    201: Trade;
};

export type TradesControllerCreateResponse = TradesControllerCreateResponses[keyof TradesControllerCreateResponses];

export type TradesControllerRemoveData = {
    body?: never;
    path: {
        /**
         * UUID do trade
         */
        id: string;
    };
    query?: never;
    url: '/trades/{id}';
};

export type TradesControllerRemoveResponses = {
    /**
     * Trade removido com sucesso.
     */
    200: unknown;
};

export type TradesControllerFindOneData = {
    body?: never;
    path: {
        /**
         * UUID do trade
         */
        id: string;
    };
    query?: never;
    url: '/trades/{id}';
};

export type TradesControllerFindOneResponses = {
    /**
     * Trade encontrado.
     */
    200: Trade;
};

export type TradesControllerFindOneResponse = TradesControllerFindOneResponses[keyof TradesControllerFindOneResponses];

export type TradesControllerUpdateData = {
    body: UpdateTradeDto;
    path: {
        /**
         * UUID do trade
         */
        id: string;
    };
    query?: never;
    url: '/trades/{id}';
};

export type TradesControllerUpdateErrors = {
    /**
     * Volume reduzido viola o total de hedges ativos.
     */
    400: unknown;
};

export type TradesControllerUpdateResponses = {
    /**
     * Trade atualizado com sucesso.
     */
    200: Trade;
};

export type TradesControllerUpdateResponse = TradesControllerUpdateResponses[keyof TradesControllerUpdateResponses];

export type RiskControllerGetBookRiskReportData = {
    body?: never;
    path: {
        /**
         * UUID da carteira para análise de risco
         */
        bookId: string;
    };
    query?: {
        /**
         * Simulação manual da cotação USDBRL
         */
        usdbrl?: string;
        /**
         * Simulação manual da cotação EURBRL
         */
        eurbrl?: string;
    };
    url: '/risk/books/{bookId}';
};

export type RiskControllerGetBookRiskReportResponses = {
    /**
     * Relatório consolidado de risco gerado com sucesso.
     */
    200: RiskReportResponseDto;
};

export type RiskControllerGetBookRiskReportResponse = RiskControllerGetBookRiskReportResponses[keyof RiskControllerGetBookRiskReportResponses];

export type HedgesControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/hedges';
};

export type HedgesControllerFindAllResponses = {
    /**
     * Lista de hedges retornada.
     */
    200: Array<Hedge>;
};

export type HedgesControllerFindAllResponse = HedgesControllerFindAllResponses[keyof HedgesControllerFindAllResponses];

export type HedgesControllerCreateData = {
    body: CreateHedgeDto;
    path?: never;
    query?: never;
    url: '/hedges';
};

export type HedgesControllerCreateErrors = {
    /**
     * Violação de Anti-Overhedging.
     */
    400: unknown;
};

export type HedgesControllerCreateResponses = {
    /**
     * Hedge criado com sucesso.
     */
    201: Hedge;
};

export type HedgesControllerCreateResponse = HedgesControllerCreateResponses[keyof HedgesControllerCreateResponses];

export type HedgesControllerRemoveData = {
    body?: never;
    path: {
        /**
         * UUID do hedge
         */
        id: string;
    };
    query?: never;
    url: '/hedges/{id}';
};

export type HedgesControllerRemoveResponses = {
    /**
     * Hedge removido.
     */
    200: unknown;
};

export type HedgesControllerFindOneData = {
    body?: never;
    path: {
        /**
         * UUID do hedge
         */
        id: string;
    };
    query?: never;
    url: '/hedges/{id}';
};

export type HedgesControllerFindOneResponses = {
    /**
     * Hedge encontrado.
     */
    200: Hedge;
};

export type HedgesControllerFindOneResponse = HedgesControllerFindOneResponses[keyof HedgesControllerFindOneResponses];

export type HedgesControllerUpdateData = {
    body: UpdateHedgeDto;
    path: {
        /**
         * UUID do hedge
         */
        id: string;
    };
    query?: never;
    url: '/hedges/{id}';
};

export type HedgesControllerUpdateResponses = {
    /**
     * Hedge atualizado.
     */
    200: Hedge;
};

export type HedgesControllerUpdateResponse = HedgesControllerUpdateResponses[keyof HedgesControllerUpdateResponses];
